### ISSUE TITLE
Any Documentation on how to use your library

### ISSUE THREAD

**Issue by iAviatorJose** [antwankakki/FabricView#1]

**Comment by antwankakki** [comment]
I am having midterms right now, expect documentation over the weekend

**Comment by vbauer** [comment]
:+1:

**Comment by BytesZero** [comment]
Pour this demo is also put on making best

**Comment by antwankakki** [comment]
The demo will be up as well, probably after the documentation

**Comment by antwankakki** [comment]
I know its not exactly the documentation expected, I have been drowned with school work, but I managed to clean up the library and generate javadoc, check it out on the library's website
http://antwankakki.github.io/FabricView/
I will have full on documentation made in two weeks by the latest. Again, I apologize, just a student drowned in school work.

**Comment by antwankakki** [comment]
Just added instructions on how to use it! Check out the readme!
