### ISSUE TITLE
Method to check if FabricView is changed by user

### ISSUE THREAD

**Issue by ghost** [antwankakki/FabricView#10]
There should be a method to check if FabricView is changed by user, this can be used to drive menu and other UI logics (eg: warn user there is can before they want to close activity to prompt them to save change)

**Comment by antwankakki** [comment]
Good idea!
How about an onCanvasChanged method that has an event object telling you the part of the canvas that was changed and whether or not it came from the user

**Comment by emmanuelproulx** [comment]
Now we have function isSaved() and markSaved() for this purpose.
