### ISSUE TITLE
Sample app no menu showing for addig text

### ISSUE THREAD

**Issue by mba858** [antwankakki/FabricView#11]
I followed the instructions to add fabricView in my app, but it's not showing any options to add image or change font ect.

**Comment by shokri-navid** [comment]
+1

**Comment by antwankakki** [comment]
The thing you see in the demo is an app I worked on with the library, the library itself doesn't have that

**Comment by shokri-navid** [comment]
Thanl you for your grate library but if you provide some sample code for
using this all things became awesome :😃
if i have some problem can i get help from you. And how can i share my
experiace with other users

**Comment by antwankakki** [comment]
thanks for your kind words! I am back to work on this and I will upload a sample project in the next few days! keep out on the look out for it :)
