### ISSUE TITLE
This dependency does't work correctly while I synced it with Gradle

### ISSUE THREAD

**Issue by anasq66** [antwankakki/FabricView#16]
Please let me know if the version number of Fabric View has been changed or not as I tried the -snapshot and its doenst work nor compiled to see that package. 

Many Thanks

**Comment by antwankakki** [comment]
Can you please add more details to your problem? I will be coming back to work on this more often and i just tried to create a new project and followed the steps on the github readme, it worked

**Comment by BrennanMcDonald** [comment]
Adding `compile 'com.github.antwankakki:FabricView:-SNAPSHOT'` to the build gradle threw 
`Failed to resolve: com.github.antwankakki:FabricView:-SNAPSHOT`

Thats all I got from the Gradle sync errors

**Comment by shokri-navid** [comment]
According to jitpack.io documentation I use 
```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

and then: 

```
dependencies {
    compile 'com.github.antwankakki:FabricView:-SNAPSHOT'
}
```
this works!!!! but some time android studio cannot build gradle because of cannot resolve dependancies

**Comment by langsmith** [comment]
I'm getting the same gradle sync error problem as others like @BrennanMcDonald  :(

Any thoughts @antwankakki ?

**Comment by antwankakki** [comment]
Sorry yall, I'm back to work on the project :) 

Looks like the issue could come from two places, either you placed the         maven { url "https://jitpack.io" }
in the wrong place or you were using the wrong dependencies tag line. in your project build.gradle, put this


```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

in your Module's build.gradle put this:
`compile 'com.github.antwankakki:FabricView:latest'`
